/* 6-1
If set A = {L M N O P} and set B = {P Q R S T}, what sets are generated by the following
operations?
• A union B
• A union all B
• A intersect B
• A except B */

/*
L M N O P Q R S T
L M N O P P Q R S T
P
L M N O 
*/

/*6-2
Write a compound query that finds the first and last names of all individual customers
along with the first and last names of all employees.*/

SELECT fname, lname
FROM individual
UNION
SELECT fname, lname
FROM employee ;

/*6-3
Sort the results from Exercise 6-2 by the lname column. */

SELECT fname, lname
FROM individual
UNION
SELECT fname, lname
FROM employee 
ORDER BY lname;